# serverless.yml

service: serverless-http

provider:
  name: aws
  runtime: python3.6
  region: eu-north-1
  memorySize: 512

functions:
  hello:
    handler: handler.hello
    events:
    - http:
        path: hello
        method: get
  goodbye:
    handler: handler.goodbye
    events:
    - http:
        path: goodbye
        method: get

plugins:
- serverless-domain-manager

custom:
  customDomain:
    domainName: 'serverless-test.MY-DOMAIN-NAME-HERE.net'
    basePath: ''
    certificateName: 'MY-DOMAIN-NAME-HERE.net'
    stage: ${self:provider.stage}
    createRoute53Record: true
